### ISSUE TITLE
make sendCommand public

### ISSUE THREAD

**Issue by prabirshrestha** [runoshun/tscompletejob#1]
I would like to get tscomplete job working in [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim)

Would it be possible to expose a public method to send command to ts? It would be great if was async with callbacks so that we can avoid `waitResponse` method.

```vim
call tscompletejob#sendCommand({
    \ 'name': 'complete',
    \ 'arguments': { ... },
    \ 'on_response': function('s:on_response')
    \ }

function! s:on_response(res)
endfunction
```

**Comment by runoshun** [comment]
Thanks for the suggestion. I've added `tscompletejob#send_command()` and `tscompletejob#complete_with_handler()`.  Please see 8a36e81.

You can pass the funcref to these functions like following.
```vim
function! Callback(success, response)
    " do something
endfunction
call tscompletejob#complete_with_handler(0, "", funcref('Callback'))
```

I hope that these are useful in your project.

**Comment by prabirshrestha** [comment]
Wow. That was faster than I expected. Thanks.

Here is the source https://github.com/prabirshrestha/asyncomplete-tscompletejob.vim

Here is it working :)

![typescript-asyncomplete](https://cloud.githubusercontent.com/assets/287744/22629537/dc452a70-eb9c-11e6-8c03-07a8ab0ce02c.gif)

One minor thing I noticed was that there is no id's which means sort of impossible to detect which callback was fired due to the async nature.
In the mean time I solved this by using lambdas. https://github.com/prabirshrestha/asyncomplete-tscompletejob.vim/blob/cf6f4410fb30d0fa59ba2070adb0684751bd9490/autoload/asyncomplete/sources/tscompletejob.vim#L11-L24

```
    call tscompletejob#complete_with_handler(0, '', {success, response->s:on_complete(success, response, a:opt, a:ctx)})
```

**Comment by prabirshrestha** [comment]
closing this for now since it works in vim8. neovim will soon have lambda support so I'm not worried about it at least for now since my main editor is still vim8. Feel free to reopen if you would like too.

**Comment by runoshun** [comment]
I added request_id parameter to `complete_with_handler` and it's callback.
But, the signature of callback must be changed, so, I send PR to your asyncomplete-tscompletejob.vim[https://github.com/prabirshrestha/asyncomplete-tscompletejob.vim] for it's changes.

**Comment by prabirshrestha** [comment]
@runoshun looks good, but is there a way to detect if the response is an error or a success?

**Comment by prabirshrestha** [comment]
@runoshun after playing with the asyncomplete and tscompletejob for a week at work on large codebase I noticed that the after typing few keywords initial hangs vim. The only way for me to prevent this is first time I open vim with a ts file, call go to definition so the server is warmed up and then start typing. But there are lot of times when I forget to follow this order and my vim instance always crashes.

Wrote a small patch here https://github.com/prabirshrestha/asyncomplete-tscompletejob.vim/commit/5eedc54022ffdc44fc1f4e7e13271ec19513a3a0. This seems to work but would be good to have some api exposed that I could call instead of this hack.

Also should `s:ensureReload` also be pure async with callback?

**Comment by runoshun** [comment]
@prabirshrestha  Thanks for your report. Unfortunately, I couldn't reproduce it. 
But, I found some bug in response handler and fix it. And though it is work around, I added `g:tscompletejob_load_on_buf_open` option (enabled by default). When this option is enabled, tscompletejob sends `open` and `reload` requests at `BufRead` of *.ts.

Could you try these functions, and check if the problem is still occurring?

**Comment by prabirshrestha** [comment]
Seems to be better. I still have the status check though.

Occasionally I seem to get the following error on Vim8 any idea why? But this doesn't seem like a big blocker at all.

![image](https://cloud.githubusercontent.com/assets/287744/22988959/ce9d587e-f368-11e6-8115-0bd44a049c62.png)

Seems to be something to do with ` if a:msg =~ "^No content"` in `s:onOut`

**Comment by runoshun** [comment]
Sorry for the late reply. Can you reproduce that error yet? Then, please tell me your environments/contents.

I think line:49 of `s:onOut` is `echoerr v:exception`, so the error will be occurred in parsing response.

**Comment by prabirshrestha** [comment]
closing this, since i don't see this. Will reopen or file new bugs if I see it.
