### ISSUE TITLE
sleep makes the UI unreponsiveness

### ISSUE THREAD

**Issue by prabirshrestha** [runoshun/tscompletejob#4]
Would it be possible to avoid using `sleep 50m` and use callback methods instead?
I have noticed that first time I go to a definition in large codebase it is very slow and the UI is not responsive. It defeats the whole purpose of async ui.

**Comment by runoshun** [comment]
Thank you for the comment.
 I modified to use async callback instead of `waitResponse` in some read only commands like `goto_definition` in 52de8fa.

if you have any comments, please let me know.

**Comment by prabirshrestha** [comment]
Thanks for the fix. I tried it and it works. I can press goto on the same large codebase and navigate around the cursor if it takes too long.
