### ISSUE TITLE
Support tags

### ISSUE THREAD

**Issue by lulu-berlin** [runoshun/tscompletejob#9]
Awesome plugin! :)

I thought it would be nice to have a way to switch back after doing `<C-]>` to follow a definition with `<C-t>`.

**Comment by runoshun** [comment]
Thank you for your feedback. I added tagstack like feature in f2df23c.
Please execute or write to .vimrc following. 
```
let g:tscompletejob_enable_tagstack = 1
```
Then, you can follow history by `<C-t>` or `:TsCompleteJobGotoPrev` / `:TsCompleteJobGotoNext` after `<C-]>`.

**Comment by prabirshrestha** [comment]
jumping next is same and different file works, but jumping to prev works only for same files.

**Comment by runoshun** [comment]
@prabirshrestha thank you for reporting bug, I fix it

**Comment by prabirshrestha** [comment]
Verified that it works. Thanks for the quick fix. Feel free to close this issue.
